---

- name: Disable pinned Docker version
  ansible.builtin.file:
    dest: "/etc/apt/preferences.d/docker.pref"
    state: "absent"
  when: not docker__version | d()

- name: Disable pinned Docker Compose v2 version
  ansible.builtin.file:
    dest: "/etc/apt/preferences.d/docker-compose-plugin.pref"
    state: "absent"
  when: not docker__compose_version | d()

- name: Enable pinned Docker version
  ansible.builtin.template:
    src: "etc/apt/preferences.d/docker.pref.j2"
    dest: "/etc/apt/preferences.d/docker.pref"
    owner: "root"
    group: "root"
    mode: "0644"
  when: docker__version | d()

- name: Enable pinned Docker Compose v2 version
  ansible.builtin.template:
    src: "etc/apt/preferences.d/docker-compose-plugin.pref.j2"
    dest: "/etc/apt/preferences.d/docker-compose-plugin.pref"
    owner: "root"
    group: "root"
    mode: "0644"
  when: docker__compose_version | d()

- name: Install Docker's dependencies
  retries: 20
  delay: 15
  ansible.builtin.apt:
    name: "{{ docker__package_dependencies }}"

- name: Add Docker's public GPG key to the APT keyring
  ansible.builtin.apt_key:
    id: "{{ docker__apt_key_id }}"
    url: "{{ docker__apt_key_url }}"

- name: Configure Docker's upstream APT repository
  ansible.builtin.apt_repository:
    repo: "{{ docker__apt_repository }}"
    update_cache: true

- name: Create Docker configuration directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - "/etc/docker"
    - "/etc/systemd/system/docker.service.d"

- name: Configure Docker daemon options (json)
  ansible.builtin.template:
    src: "etc/docker/daemon.json.j2"
    dest: "/etc/docker/daemon.json"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: ["Restart Docker"]

- name: Install Docker and Docker Compose
  retries: 20
  delay: 15
  ansible.builtin.apt:
    name:
      - "docker-{{ docker__edition }}"
      - "docker-compose-plugin"
    state: "{{ docker__state }}"

- name: Install Docker python package
  retries: 20
  delay: 15
  ansible.builtin.apt:
    name:
      - "python3-docker"
    state: present

- name: Add user(s) to "docker" group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "docker"
    append: true
  loop: "{{ docker__users }}"

- name: Configure containerd options
  template:
    src: "etc/containerd/config.toml.j2"
    dest: "/etc/containerd/config.toml"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: ["Restart Docker"]

- name: Configure Docker daemon options (flags)
  ansible.builtin.template:
    src: "etc/systemd/system/docker.service.d/options.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/options.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: ["Reload systemd daemon", "Restart Docker"]

- name: Configure Docker daemon environment variables
  ansible.builtin.template:
    src: "etc/systemd/system/docker.service.d/environment.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/environment.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: ["Reload systemd daemon", "Restart Docker"]

- name: Configure custom systemd unit file override
  ansible.builtin.template:
    src: "etc/systemd/system/docker.service.d/custom.conf.j2"
    dest: "/etc/systemd/system/docker.service.d/custom.conf"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: ["Reload systemd daemon", "Restart Docker"]

- name: Restart Docker now to make sure `docker login` works
  ansible.builtin.meta: "flush_handlers"

# It's safe to ignore no-log-password because we're removing the password from
# the output with the loop_control property.
- name: Manage Docker registry login credentials
  ansible.builtin.docker_login:  # noqa no-log-password
    registry_url: "{{ item.registry_url | d(omit) }}"
    username: "{{ item.username }}"
    password: "{{ item.password }}"
    email: "{{ item.email | d(omit) }}"
    reauthorize: "{{ item.reauthorize | d(omit) }}"
    config_path: "{{ item.config_path | d(omit) }}"
    state: "{{ item.state | d('present') }}"
  loop: "{{ docker__registries }}"
  loop_control:
    label: '{{ {"registry_url": item.registry_url | d("https://index.docker.io/v1/"), "username": item.username, "state": item.state | d("present")} }}'
  when: item.username | d() and item.password | d()
  become: true
  become_user: "{{ docker__login_become_user | d('root') }}"

- name: Remove Docker related cron jobs
  ansible.builtin.file:
    path: "/etc/cron.d/{{ item.cron_file }}"
    state: "absent"
  loop: "{{ docker__cron_jobs }}"
  when:
    - item.state | d("present") == "absent"
    - item.cron_file | d()

- name: Create Docker related cron jobs
  ansible.builtin.cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    minute: "{{ item.schedule[0] }}"
    hour: "{{ item.schedule[1] }}"
    day: "{{ item.schedule[2] }}"
    month: "{{ item.schedule[3] }}"
    weekday: "{{ item.schedule[4] }}"
    cron_file: "{{ item.cron_file }}"
    user: "{{ item.user | d('root') }}"
  loop: "{{ docker__cron_jobs }}"
  when:
    - item.state | d("present") != "absent"
    - item.name | d() and item.job | d()
    - item.schedule | d() and item.cron_file | d()
